# Generated by Django 3.2.8 on 2021-10-30 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Abilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name_plural": "Abilities",
            },
        ),
        migrations.CreateModel(
            name="HeldItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name_plural": "HeldItems",
            },
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poke_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=50)),
                ("height", models.FloatField()),
                ("weight", models.FloatField()),
                ("image", models.CharField(max_length=500)),
                ("created", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Pokemon",
            },
        ),
        migrations.CreateModel(
            name="Types",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name_plural": "Types",
            },
        ),
        migrations.CreateModel(
            name="PokeTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokemons.pokemon",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pokemons.types"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PokeTypes",
            },
        ),
        migrations.CreateModel(
            name="PokeStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baseStat", models.FloatField(default=0)),
                ("effort", models.FloatField(default=0)),
                ("name", models.CharField(default="", max_length=20)),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokemons.pokemon",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PokeStats",
            },
        ),
        migrations.CreateModel(
            name="PokeHeldItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "heldItem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokemons.helditems",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokemons.pokemon",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PokeHeldItems",
            },
        ),
        migrations.CreateModel(
            name="PokeEvolutions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("order", models.PositiveIntegerField()),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokemons.pokemon",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PokeEvolutions",
            },
        ),
        migrations.CreateModel(
            name="PokeAbilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokemons.abilities",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokemons.pokemon",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PokeAbilities",
            },
        ),
    ]
