FROM node:10.23.3-alpine as web
RUN apk update && apk add bash
RUN mkdir -p /home/frontend
WORKDIR /home/frontend
COPY frontend/package.json /home/frontend/
COPY frontend/yarn.lock /home/frontend/
RUN yarn install
COPY ./frontend ./frontend/
EXPOSE 3000
